_format_version: "3.0"
_transform: true

services:
  - name: auth-service
    url: http://estate-service:9001/auth
    routes:
      - name: auth-routes
        paths:
          - /api/auth
        strip_path: true
        plugins:
          - name: cors
            config:
              origins:
                - http://localhost:3000
                - http://localhost:5173
                - http://localhost:8000
              methods:
                - GET
                - POST
                - PUT
                - PATCH
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - Authorization
              exposed_headers:
                - X-Auth-Token
              credentials: true
              max_age: 3600

  - name: estate-service
    url: http://estate-service:9001
    routes:
      - name: estate-routes
        paths:
          - /api/estate
        strip_path: true
        preserve_host: false
        protocols:
          - http
          - https
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        plugins:
          - name: cors
            config:
              origins:
                - http://localhost:3000
                - http://localhost:5173
                - http://localhost:8000
              methods:
                - GET
                - POST
                - PUT
                - PATCH
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - Authorization
              exposed_headers:
                - X-Auth-Token
              credentials: true
              max_age: 3600
          - name: rate-limiting
            config:
              minute: 100
              hour: 1000
              day: 10000
              policy: local
              hide_client_headers: false
              fault_tolerant: true

  - name: contract-service
    url: http://contract-service:9002
    routes:
      - name: contract-routes
        paths:
          - /api/contract
        strip_path: true
        preserve_host: false
        protocols:
          - http
          - https
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        plugins:
          - name: cors
            config:
              origins:
                - http://localhost:5173
                - http://localhost:8000
              methods:
                - GET
                - POST
                - PUT
                - PATCH
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - Authorization
              exposed_headers:
                - X-Auth-Token
              credentials: true
              max_age: 3600
          - name: rate-limiting
            config:
              minute: 200
              hour: 2000
              day: 20000
              policy: local
              hide_client_headers: false
              fault_tolerant: true
  - name: chat-service
    url: http://chat-service:9003
    routes:
      - name: chat-routes
        paths:
          - /api/chat
        strip_path: true
        preserve_host: false
        protocols:
          - http
          - https
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        plugins:
          - name: cors
            config:
              origins:
                - http://localhost:5173
                - http://localhost:8000
              methods:
                - GET
                - POST
                - PUT
                - PATCH
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - Authorization
              exposed_headers:
                - X-Auth-Token
              credentials: true
              max_age: 3600
          - name: rate-limiting
            config:
              minute: 150
              hour: 1500
              day: 15000
              policy: local
              hide_client_headers: false
              fault_tolerant: true
  - name: notification-service
    url: http://notification-service:9004
    routes:
      - name: notification-routes
        paths:
          - /api/notification
        strip_path: true
        preserve_host: false
        protocols:
          - http
          - https
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        plugins:
          - name: cors
            config:
              origins:
                - http://localhost:5173
                - http://localhost:8000
              methods:
                - GET
                - POST
                - PUT
                - PATCH
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - Authorization
              exposed_headers:
                - X-Auth-Token
              credentials: true
              max_age: 3600
          - name: rate-limiting
            config:
              minute: 150
              hour: 1500
              day: 15000
              policy: local
              hide_client_headers: false
              fault_tolerant: true
    