_format_version: "3.0"
_transform: true

services:
  - name: estate-service
    url: http://estate-service:9001
    routes:
      - name: estate-routes
        paths:
          - /estate
        strip_path: true
        preserve_host: false
        protocols:
          - http
          - https
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE

  - name: contract-service
    url: http://contract-service:9002
    routes:
      - name: contract-routes
        paths:
          - /contract
        strip_path: true
        preserve_host: false
        protocols:
          - http
          - https
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE

plugins:
  - name: rate-limiting
    route: estate-routes
    config:
      minute: 100
      hour: 1000
      day: 10000
      policy: local
      hide_client_headers: false
      fault_tolerant: true

  - name: rate-limiting
    route: contract-routes
    config:
      minute: 200
      hour: 2000
      day: 20000
      policy: local
      hide_client_headers: false
      fault_tolerant: true

  - name: rate-limiting
    config:
      minute: 300
      hour: 3000
      day: 30000
      policy: local
      hide_client_headers: false
      fault_tolerant: true